fix: relax signer compatible check
instanceof operator does not work reliably as the Signer instance can be
created from another ethers package in the dependency tree. and it causes
the following error:

TypeError: __classPrivateFieldGet(...).getNetwork is not a function
      at EthersAdapter.getChainId (/Users/rfeng/Projects/collabland/collabland-monorepo/components/ethereum/node_modules/@safe-global/safe-ethers-lib/src/EthersAdapter.ts:90:34)
      at ContractManager.init (/Users/rfeng/Projects/collabland/collabland-monorepo/components/ethereum/node_modules/@safe-global/safe-core-sdk/src/managers/contractManager.ts:39:38)

Signed-off-by: Raymond Feng <enjoyjava@gmail.com>